<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class SociallinkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sociallinks')->insert([
            [
                "link"=>"#",
                "icon_id"=>1,
                "chef_id"=>1,
            ],
            [
                "link"=>"#",
                "icon_id"=>2,
                "chef_id"=>1,
            ],
            [
                "link"=>"#",
                "icon_id"=>3,
                "chef_id"=>1,
            ],
            [
                "link"=>"#",
                "icon_id"=>4,
                "chef_id"=>1,
            ],
            [
                "link"=>"#",
                "icon_id"=>5,
                "chef_id"=>1,
            ],
            [
                "link"=>"#",
                "icon_id"=>1,
                "chef_id"=>2,
            ],
            [
                "link"=>"#",
                "icon_id"=>2,
                "chef_id"=>2,
            ],
            [
                "link"=>"#",
                "icon_id"=>3,
                "chef_id"=>2,
            ],
            [
                "link"=>"#",
                "icon_id"=>4,
                "chef_id"=>2,
            ],
            [
                "link"=>"#",
                "icon_id"=>5,
                "chef_id"=>2,
            ],
            [
                "link"=>"#",
                "icon_id"=>1,
                "chef_id"=>3,
            ],
            [
                "link"=>"#",
                "icon_id"=>2,
                "chef_id"=>3,
            ],
            [
                "link"=>"#",
                "icon_id"=>3,
                "chef_id"=>3,
            ],
            [
                "link"=>"#",
                "icon_id"=>4,
                "chef_id"=>3,
            ],
            [
                "link"=>"#",
                "icon_id"=>5,
                "chef_id"=>3,
            ],
            [
                "link"=>"#",
                "icon_id"=>1,
                "chef_id"=>4,
            ],
            [
                "link"=>"#",
                "icon_id"=>2,
                "chef_id"=>4,
            ],
            [
                "link"=>"#",
                "icon_id"=>3,
                "chef_id"=>4,
            ],
            [
                "link"=>"#",
                "icon_id"=>4,
                "chef_id"=>4,
            ],
            [
                "link"=>"#",
                "icon_id"=>5,
                "chef_id"=>4,
            ],
 
            ]);
    }
}
